# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Telemetrix For The ESP32
repo_url: https://github.com/MrYsLab/telemetrix-esp32
copyright: > # should remain a link to the original theme
  Copyright &copy; 2020-2023 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last 
  Modified: November 14, 2023
nav:
    - Introduction: index.md
    - System Requiements:
        - Python 3: python3.md
        - Arduino IDE: arduino_ide.md
    - Installing The Client Software: install_telemetrix.md
    - Installing The Server Software: server.md
    - Usage:
        - The APIs And The Examples: api.md
        - Specifying Pin Modes And Pin Numbers: pins.md
        - Understanding Callbacks: callback.md
    - Reporting Issues: about.md
    - License: license.md

# markdown_extensions:
#     - toc:
#         permalink: "#"
# theme: windmill
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
