# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Telemetrix For The ESP32
repo_url: https://github.com/MrYsLab/telemetrix-esp32
copyright: > # should remain a link to the original theme
  Copyright &copy; 2020-2025 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last 
  Modified: May 31, 2025
nav:
    - Introduction: index.md
    - System Requiements:
        - Python 3: python3.md
        - Arduino IDE: arduino_ide.md
    - Installing The Client Software: install_telemetrix.md
    - Installing The Server Software: server.md
    - Usage:
        - The APIs And The Examples: api.md
        - Specifying Pin Modes And Pin Numbers: pins.md
        - Understanding Callbacks: callback.md
    - Adding New Features: extend.md
    - Reporting Issues: about.md
    - License: license.md

# markdown_extensions:
#     - toc:
#         permalink: "#"
# theme: windmill
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer


plugins:
  - search
  - open-in-new-tab

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:MisterYsLab@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/MrYsLab
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/mryslab.bsky.social

